In [1]:
import torch, random, math, time, sys, os, tqdm
import numpy as np
import numba

In [77]:
from trainer.classification import Trainer
from trainer.attention_approx import Trainer as ApproxTrainer
batch_size = 8

trainer = Trainer(batch_size=batch_size)
trainer.load()
trainer.model.eval()
bert = trainer.model.bert
fc = trainer.model.classifier
batch = trainer.get_batch()
test_batch = trainer.get_batch(test=False)

approx_trainer = ApproxTrainer(batch_size=batch_size, factor=16)
approx_trainer.load()
approx_bert = approx_trainer.bert
approx_bert = approx_bert.eval()

100%|██████████| 7600/7600 [00:00<00:00, 211094.26it/s]


Classification Dataset Stat.: name:AG_NEWS, nclass:5, max_len:1012, avg_len:236.477525, count:120000
Classification Dataset Stat.: name:AG_NEWS, nclass:5, max_len:892, avg_len:235.2992105263158, count:7600


Some weights of the model checkpoint at google/bert_uncased_L-4_H-256_A-4 were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Trainer.__init__: Model initialized. model = bert
Trainer.load: Loading...


100%|██████████| 7600/7600 [00:00<00:00, 200019.52it/s]


Classification Dataset Stat.: name:AG_NEWS, nclass:5, max_len:1012, avg_len:236.477525, count:120000
Classification Dataset Stat.: name:AG_NEWS, nclass:5, max_len:892, avg_len:235.2992105263158, count:7600


Some weights of the model checkpoint at google/bert_uncased_L-4_H-256_A-4 were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Trainer.__init__: Model initialized. model = bert
Trainer.load: Loading...


In [78]:
import importlib
import models.sparse_token as sparse
importlib.reload(sparse)

<module 'models.sparse_token' from 'f:\\Library\\discrete_edge_learning\\models\\sparse_token.py'>

In [133]:
sparse_bert = sparse.SparseBertModel(bert.config)
sparse_bert.to(trainer.device)
sparse_bert.eval()
sparse_bert.load_state_dict(bert.state_dict())

<All keys matched successfully>

In [159]:
def eval_fc(lm_output, fc=fc, batch=batch):
    last_hidden = lm_output.last_hidden_state[:,0,:]
    x = fc(last_hidden)
    return torch.argmax(x, dim=-1), batch.labels, lm_output

def eval(bert, fc=fc, batch=batch):
    lm_output = bert(
        input_ids = batch.input_ids, 
        attention_mask = batch.attention_masks,
        output_hidden_states = True,
        output_attentions = True,
    )
    return eval_fc(lm_output, fc=fc, batch=batch)

def approx_eval(sparse_bert, approx_bert, fc=fc, batch=batch):
    lm_output = sparse.run_bert_with_approx(
        sparse_bert, 
        approx_bert, 
        {
            'input_ids': batch.input_ids,
            'attention_mask': batch.attention_masks,
            'output_hidden_states': True,
            'output_attentions': True,
        },
        ks = [0.35]*4,
    )
    return eval_fc(lm_output, fc=fc, batch=batch)
    
eval(bert)[:2], approx_eval(sparse_bert, approx_bert)[:2]

((tensor([1, 2, 4, 1, 3, 4, 3, 3], device='cuda:0'),
  tensor([1, 2, 4, 1, 3, 4, 3, 3], device='cuda:0')),
 (tensor([1, 2, 4, 1, 3, 4, 3, 3], device='cuda:0'),
  tensor([1, 2, 4, 1, 3, 4, 3, 3], device='cuda:0')))

In [165]:
importlib.reload(sparse)
def accuracy(batch_eval, N=10):
    trainer.seed()
    trainer.dataset.batch_size = 256
    acc_sum = 0
    for i in tqdm.tqdm(range(N)):
        batch = trainer.get_batch(test=True)
        with torch.no_grad():
            output, label, _ = batch_eval(batch)
        acc_sum += torch.mean((output == label) * 1.0)
    return acc_sum.item() / N

# setup for evaluation
sparse_bert = sparse.SparseBertModel(bert.config)
sparse_bert.to(trainer.device)
sparse_bert.eval()
sparse_bert.load_state_dict(bert.state_dict())
sparse.set_print(sparse_bert, False)
sparse.set_backup_last_inputs(sparse_bert, False)
sparse.set_output_masking(sparse_bert, False)

sparse_bert = sparse_bert.to(trainer.device)
approx_bert = approx_bert.to(trainer.device)
bert = bert.to(trainer.device)
sparse.set_print(sparse_bert, False)
sparse.set_backup_last_inputs(sparse_bert, False)
sparse.set_output_masking(sparse_bert, False)

sparse.timer_reset()
acc_bert = acc_approx = accuracy(lambda batch: approx_eval(sparse_bert, approx_bert, batch=batch))
#acc_bert = accuracy(lambda batch: eval(bert, batch=batch))
sparse.timer_report()
acc_bert, acc_approx, abs(acc_approx - 0.93046875) < 0.001
#(0.934375, 0.92203125)
#(0.934375, 0.93359375)
# 0.8486328125

100%|██████████| 10/10 [00:01<00:00,  8.54it/s]

approx_att                : 0:00:00.039991 (29.84%)
approx_mask_reset         : 0:00:00.002000 (1.49%)
approx_mask_reset_inverse : 0:00:00.001000 (0.75%)
approx_mask_update        : 0:00:00.008003 (5.97%)
approx_sparse             : 0:00:00.056001 (41.79%)
attention.probs.dropout   : 0:00:00 (0.00%)
attention.qkv             : 0:00:00.026000 (19.40%)
attention.scores.matmul   : 0:00:00.001002 (0.75%)


(0.930859375, 0.930859375, True)

In [87]:
def benchmark(eval, batch_size=8, N=100, WARM=20, amp=False, device=trainer.device):
    assert WARM < (N * 0.33)
    trainer.dataset.batch_size = batch_size
    batch = trainer.get_batch(test=True)
    batch = batch.to(device)
    assert batch.input_ids.shape[0] == batch_size
    for i in tqdm.tqdm(range(N)):
        if i == WARM: t = time.time()
        with torch.no_grad(), torch.cuda.amp.autocast(enabled=amp):
            eval(batch)
    t = time.time() - t
    t_item = t / (batch_size * (N-WARM))
    return t, t_item * 1000, 1.0/t_item

In [168]:
importlib.reload(sparse)
sparse.timer_reset()
benchmark_device = 'cpu'

sparse_bert = sparse.SparseBertModel(bert.config)
sparse_bert.to(benchmark_device)
sparse_bert.eval()
sparse_bert.load_state_dict(bert.state_dict())
sparse.set_print(sparse_bert, False)
sparse.set_backup_last_inputs(sparse_bert, False)
sparse.set_output_masking(sparse_bert, False)

sparse_bert=sparse_bert.to(benchmark_device)
approx_bert=approx_bert.to(benchmark_device)
time_approx = benchmark(
    eval = lambda batch: approx_eval(sparse_bert, approx_bert, batch=batch, fc=lambda x: x),
    batch_size = 32,
    WARM = 1,
    N = 25,
    device = benchmark_device,
)
sparse.timer_report()
time_approx

100%|██████████| 25/25 [00:08<00:00,  3.02it/s]

approx_att                : 0:00:01.887025 (19.95%)
approx_mask_reset         : 0:00:00.051972 (0.55%)
approx_mask_reset_inverse : 0:00:00.003994 (0.04%)
approx_mask_update        : 0:00:00.171000 (1.81%)
approx_sparse             : 0:00:06.131067 (64.82%)
attention.probs.dropout   : 0:00:00.003995 (0.04%)
attention.qkv             : 0:00:00.895014 (9.46%)
attention.scores.matmul   : 0:00:00.315021 (3.33%)


(7.959080457687378, 10.363386012613773, 96.49355903397327)

In [131]:
bert = bert.to(benchmark_device)
time_bert = benchmark(
    lambda batch: eval(bert, batch=batch, fc=lambda x: x), 
    batch_size = 32,
    WARM = 1,
    N=25,
    device = benchmark_device
)
time_bert

100%|██████████| 25/25 [00:04<00:00,  5.80it/s]


(4.133043050765991, 5.381566472351551, 185.81950165209722)

In [153]:
torch.ones(2,2).unsqueeze(-1).repeat(1, 1, 12)

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])